inherit_gem:
  rubocop-fnando: .rubocop-rails.yml

AllCops:
  TargetRubyVersion: 3.2
  TargetRailsVersion: 7.1
  NewCops: enable

Metrics:
  Enabled: false
Layout/LineLength:
  Enabled: true
  Max: 120